### ISSUE TITLE
Text in view manage-workshop is not diplayed correctly

### ISSUE THREAD

**Issue by dhrunia** [Virtual-Labs/outreach-portal#14]
The text for Experiments and Participants in In the view site/outreachcoordinator/manage-workshop is only partially visible and overlaps into adjacent box.

**Comment by manjulasoftware** [comment]
Fixed

**Comment by dhrunia** [comment]
It is still not fixed.

![1](https://cloud.githubusercontent.com/assets/7869622/9631015/a1ceb97a-519b-11e5-9787-85f7ce7501b9.png)

**Comment by manjulasoftware** [comment]
fixed please check once. 
![screenshot_2](https://cloud.githubusercontent.com/assets/13532745/9631923/b6c486ce-51a1-11e5-9d5b-b3347e0e3e55.png)
